let catalog=[
{id:1,n:'Espresso',p:95,c:'kahve',i:'☕',b:'86910001'},{id:2,n:'Latte',p:185,c:'kahve',i:'🥛',b:'86910002'},{id:3,n:'Türk Kahvesi',p:120,c:'kahve',i:'☕',b:'86910003'},{id:4,n:'Flat White',p:170,c:'kahve',i:'☕',b:'86910004'},{id:5,n:'Limonata',p:120,c:'icecek',i:'🍋',b:'86920001'},{id:6,n:'Soğuk Kahve',p:195,c:'icecek',i:'🧊',b:'86920002'},{id:7,n:'Peynirli Burger',p:320,c:'yemek',i:'🍔',b:'86930001'},{id:8,n:'Pizza',p:390,c:'yemek',i:'🍕',b:'86930002'},{id:9,n:'Makarna',p:340,c:'yemek',i:'🍝',b:'86930003'},{id:10,n:'Tiramisu',p:190,c:'tatli',i:'🍰',b:'86940001'},{id:11,n:'Cheesecake',p:210,c:'tatli',i:'🍰',b:'86940002'},{id:12,n:'Kahve + Tatlı Menü',p:330,c:'menu',i:'🎁',b:'86950001'}];
let items=[],currentCat='all',online=navigator.onLine,qtyBuffer='',held=JSON.parse(localStorage.getItem('faleora_pos_held')||'[]'),queue=JSON.parse(localStorage.getItem('faleora_pos_queue')||'[]');
const money=v=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(v);
function drawProducts(list=catalog){document.getElementById('products').innerHTML=list.map(x=>"<button class='product' onclick='add("+x.id+")'><span class='price'>"+money(x.p)+"</span><div style='font-size:30px'>"+x.i+"</div><strong>"+x.n+"</strong><small>"+x.b+"</small></button>").join('')}
function filterCat(c,b){currentCat=c;document.querySelectorAll('.cat button').forEach(x=>x.classList.remove('on'));b.classList.add('on');searchProducts()}
function searchProducts(){let q=(document.getElementById('search').value||'').toLocaleLowerCase('tr');drawProducts(catalog.filter(x=>(currentCat==='all'||x.c===currentCat)&&(!q||x.n.toLocaleLowerCase('tr').includes(q)||x.b.includes(q))))}
function add(id){const p=catalog.find(x=>x.id===id),qty=Math.max(1,parseInt(qtyBuffer||'1'));qtyBuffer='';const old=items.find(x=>x.id===id);old?old.q+=qty:items.push({...p,q:qty});render()}
function render(){const total=items.reduce((s,x)=>s+x.p*x.q,0);document.getElementById('cart').innerHTML=items.length?items.map((x,i)=>"<div class='line'><div><b>"+x.q+" × "+x.n+"</b><small>"+money(x.p)+" / adet</small></div><div><b>"+money(x.p*x.q)+"</b><br><button class='chip' onclick='removeItem("+i+")'>Sil</button></div></div>").join(''):"<p class='note'>Sepet boş. Ürün seçerek satışa başlayın.</p>";document.getElementById('total').textContent=money(total);updateNet()}
function removeItem(i){items.splice(i,1);render()}function removeLast(){items.pop();render()}function qtyKey(n){qtyBuffer=(qtyBuffer+n).slice(-3);msg('Adet: '+qtyBuffer)}
function clearSale(){items=[];qtyBuffer='';render();msg('Yeni satış hazır.')}
function holdSale(){if(!items.length)return msg('Bekletilecek satış yok.');held.push({id:crypto.randomUUID?crypto.randomUUID():Date.now(),at:new Date().toISOString(),items});localStorage.setItem('faleora_pos_held',JSON.stringify(held));items=[];render();msg('Satış beklemeye alındı. Bekleyen: '+held.length)}
async function sendKitchen(){if(!items.length)return msg('Mutfak için ürün yok.');if(window.FaleoraApi&&FaleoraApi.configured()&&online){try{const ref='kds-'+Date.now()+'-'+Math.random().toString(36).slice(2);const sale=await FaleoraApi.post('/api/sales',{client_ref:ref,venue_id:1,source:'pos',items:items.map(x=>({product_id:x.id,name:x.n,qty:x.q,unit_price:x.p,station:'kitchen',modifiers:[]}))});await FaleoraApi.post('/api/sales/'+sale.id+'/send-kitchen',{});msg('✓ Sipariş #'+sale.id+' mutfağa gönderildi.');return}catch(e){msg('KDS API erişilemedi; yerel kuyruğa alındı: '+e.message)}}commit('KDS','Sipariş mutfağa gönderildi.')}
async function pay(method){if(!items.length)return msg('Ödeme için ürün ekleyin.');const total=items.reduce((s,x)=>s+x.p*x.q,0);if(window.FaleoraApi&&FaleoraApi.configured()&&online){try{const ref='pos-'+Date.now()+'-'+Math.random().toString(36).slice(2);const sale=await FaleoraApi.post('/api/sales',{client_ref:ref,venue_id:1,source:'pos',items:items.map(x=>({product_id:x.id,name:x.n,qty:x.q,unit_price:x.p,station:'kitchen',modifiers:[]}))});const map={'Nakit':'cash','Kart':'card','Yemek Kartı':'meal_card','Parçalı':'other'};const paid=await FaleoraApi.post('/api/sales/'+sale.id+'/payments',{method:map[method]||'other',amount:total,actor_ref:'cashier'});msg('✓ '+method+' • Satış #'+sale.id+' • '+money(total)+' • '+paid.status);items=[];render();return}catch(e){msg('API erişilemedi; işlem yerel kuyruğa alındı: '+e.message)}}commit(method,method+' ödeme kaydı oluşturuldu • '+money(total));items=[];render()}
function commit(type,note){const tx={id:crypto.randomUUID?crypto.randomUUID():'tx-'+Date.now(),type,at:new Date().toISOString(),items:JSON.parse(JSON.stringify(items)),state:online?'sent':'pending'};if(!online){queue.push(tx);localStorage.setItem('faleora_pos_queue',JSON.stringify(queue))}msg(note+(online?'':' • Çevrimdışı kuyruğa alındı'))}
function toggleNet(){online=!online;if(online)syncQueue();updateNet()}function syncQueue(){queue=queue.map(x=>({...x,state:'sent'}));queue=[];localStorage.setItem('faleora_pos_queue','[]');msg('Bekleyen yerel işlemler senkronize edildi.')}
function updateNet(){const n=document.getElementById('net'),b=document.getElementById('offlineBanner');n.textContent=online?'● ÇEVRİMİÇİ':'● ÇEVRİMDIŞI';n.className='chip '+(online?'online':'offline');b.style.display=online?'none':'block';document.getElementById('queueCount').textContent=queue.length}
function msg(t){document.getElementById('msg').innerHTML="<p class='note'>"+t+"</p>"}
async function loadCatalog(){if(window.FaleoraApi&&FaleoraApi.configured()){try{const rows=await FaleoraApi.get('/api/pos/venues/1/products');if(rows.length){catalog=rows.map(x=>({id:x.id,n:x.name,p:x.price,c:x.category,i:'◈',b:String(x.id)}));drawProducts();msg('Ürün kataloğu API üzerinden yüklendi.')}}catch(e){msg('Katalog API erişilemedi; yerel katalog kullanılıyor.')}}}
function resumeHeld(){if(!held.length)return msg('Bekleyen satış yok.');const x=held.shift();items=x.items||[];localStorage.setItem('faleora_pos_held',JSON.stringify(held));render();msg('Bekleyen satış geri açıldı. Kalan: '+held.length)}
window.addEventListener('online',()=>{online=true;syncQueue();updateNet()});window.addEventListener('offline',()=>{online=false;updateNet()});drawProducts();render();loadCatalog();